server:
  port: 8080
spring:
  application:
    name: "credibanco"
  devtools:
    add-properties: false

  profiles:
    include: null
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: "jdbc:postgresql://localhost:5432/credibanco?currentSchema=credibanco_schema"
    username: "postgres"
    password: "Salem14"
    driverClassName: "org.postgresql.Driver"

  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
